services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomdb
      TZ: Asia/Kolkata
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pg_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: Asia/Kolkata
    ports:
      - "5672:5672"    # AMQP (Spring Boot connects here)
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - pg_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      TZ: Asia/Kolkata
    networks:
      - pg_network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "8001:5540"
    volumes:
      - redis_insight_data:/db
    depends_on:
      - redis
    networks:
      - pg_network

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pg_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      TZ: Asia/Kolkata
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    networks:
      - pg_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      TZ: Asia/Kolkata
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - pg_network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    environment:
      TZ: Asia/Kolkata
    networks:
      - pg_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/ecomdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME: localhost
      TZ: Asia/Kolkata
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - pg_network
    restart: unless-stopped

# ======= APP SERVICES ====

#      // CONFIG SERVER 8888
  configserver:
   container_name: configserver
   build:
    context: ./configserver
    dockerfile: Dockerfile
   ports:
    - "8888:8888"
   environment:
     - TZ=Asia/Kolkata
     - SPRING_PROFILES_ACTIVE=docker
     - RABBIT_ADDRESS=rabbitmq:5672
     - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config/
     - SPRING_CLOUD_CONFIG_SERVER_GIT_ENABLED=false
     - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_ENABLED=false
     - SPRING_CLOUD_CONFIG_SERVER_BOOTSTRAP=false
   depends_on:
    - eureka-service
   volumes:
    - ./configserver/src/main/resources/config:/config
   networks:
    - pg_network
   restart: unless-stopped


#  EUREKA SERVICE 8761
  eureka-service:
    container_name: eureka-service
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: eureka-service
    ports:
      - "8761:8761"
    environment:
      TZ: Asia/Kolkata
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - pg_network
    restart: unless-stopped

#    //API GATEWAY
  api-gateway:
    container_name: api-gateway
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Kolkata
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-service
      - redis
      - keycloak
      - zipkin
    networks:
      - pg_network
    restart: unless-stopped


  #    // USER SERVICE 8081
  user-service:
    container_name: user-service
    build:
      context: ./userms
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      TZ: Asia/Kolkata
      SPRING_PROFILES_ACTIVE: docker
      RABBIT_ADDRESS: rabbitmq:5672
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ms_ecom_userdb
    depends_on:
      - mongo
      - rabbitmq
      - keycloak
      - eureka-service
    networks:
      - pg_network
    restart: unless-stopped

#    // PRODUCT SERVICE 8082
  product-service:
    container_name: product-service
    build:
      context: ./productms
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      TZ: Asia/Kolkata
      SPRING_PROFILES_ACTIVE: docker
      RABBIT_ADDRESS: rabbitmq:5672
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - postgres
      - rabbitmq
      - eureka-service
    networks:
      - pg_network
    restart: unless-stopped

#   // ORDER SERVICE 8083
  order-service:
    container_name: order-service
    build:
      context: ./orderms
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      TZ: Asia/Kolkata
      SPRING_PROFILES_ACTIVE: docker
      RABBIT_ADDRESS: rabbitmq:5672
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - postgres
      - rabbitmq
      - kafka
      - eureka-service
      - zipkin
    networks:
      - pg_network
    restart: unless-stopped

#  // NOTIFICATION SERVICE 8084
  notification-service:
    container_name: notification-service
    build:
      context: ./notification
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      TZ: Asia/Kolkata
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka
      - eureka-service
    networks:
      - pg_network
    restart: unless-stopped




# ======= VOLUMES =======
volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:
  redis_data:
  redis_insight_data:
  mongo_data:
  zookeeper_data:
  kafka_data:
  keycloak_data:


networks:
  pg_network:
    driver: bridge
