server:
  port: 8084

spring:
  application:
    name: notification-service

  cloud:
    function:
      definition: orderCreated

    stream:
      function:
        definition: orderCreated

      bindings:
        orderCreated-in-0:
          destination: order.exchange
          group: notification-group
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

# ======== DOCKER PROFILE ========
---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092   # âœ… container name (not localhost)

# Agar baad me RabbitMQ use karoge (Docker friendly)
# spring:
#   rabbitmq:
#     addresses: rabbitmq:5672
