server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://mongo:27017/ms_ecom_userdb
      database: ms_ecom_userdb

  rabbitmq:
    addresses: rabbitmq:5672
    connection-timeout: 30000

keycloak:
  admin:
    username: awdhesh9211
    password: admin
    serveruri: http://keycloak:8080
    realm: ecom-app
    clientId: admin-cli

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka

app:
  message: "Hello User ms"
