server:
  port: 8888

spring:
  application:
    name: configserver

  rabbitmq:
    addresses: ${RABBIT_ADDRESS}
    connection-timeout: 30000

  cloud:
    config:
      server:
        native:
          search-locations: file:/config/
#        git:
#          uri: https://github.com/Awdhesh9211/config-ecom.git
#          default-label: main
#          clone-on-start: true
#          search-paths:
#            - config    # your repo folder containing service YAMLs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka

---

# ================= DOCKER PROFILE =================
spring:
  config:
    activate:
      on-profile: native

  rabbitmq:
    addresses: ${RABBIT_ADDRESS}

  cloud:
    config:
      server:
        native:
            search-locations: file:/config/

#        git:
#          uri: https://github.com/Awdhesh9211/config-ecom.git
#          default-label: main
#          clone-on-start: true
#          search-paths:
#            - config

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
