spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888



































#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#  datasource:
#    mongodb:
#      uri: mongodb://localhost:27017/ms_ecom_userdb
#      database: ms_ecom_userdb
#
#
#server:
#  port: 8081
#  servlet:
#    context-path: /api/v1
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true
#  tracing:
#    sampling:
#      probability: 1.0   # 100% sampling (use lower in prod)
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#
#logging:
#  level:
#    root: INFO
#    com.ecommerce.userms: TRACE
#  file:
#    name: logs/user-service.log
#  pattern:
#    console: |
#
#
#      ------START--------
#      TIME  : %d{yyyy-MM-dd HH:mm:ss}%d{HH:mm:ss}
#      LEVEL : %-5level
#      PATH  : %logger
#      MSG   : %msg
#      -----END-----------
#
#
##app:
##  message: "Hello"