spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/orderdb
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        jdbc:
#          time_zone: Asia/Kolkata
#
#server:
#  port: 8083
#  servlet:
#    context-path: /api/v1
#
#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always
#  tracing:
#    sampling:
#      probability: 1.0   # 100% sampling (use lower in prod)
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#
#
#logging:
#  level:
#    root: INFO
#    com.ecommerce.userms: TRACE
#  file:
#    name: logs/order-service.log
#  pattern:
#    console: |
#
#
#      ------START--------
#      TIME  : %d{yyyy-MM-dd HH:mm:ss}
#      LEVEL : %-5level
#      PATH  : %logger
#      MSG   : %msg
#      -----END-----------
##  testing variable
##app:
##  message: "hello"
#
##logging:
##  level:
##    org.springdoc: DEBUG
#
##springdoc:
##  api-docs:
##    path: /api-docs
##  swagger-ui:
##    path: /swagger-ui.html
##    operationsSorter: method
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      productService:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        slidingWindowType: COUNT_BASED
#        automaticTransitionFromOpenToHalfOpenEnabled: true
##        recordExceptions:
##          - org.springframework.web.client.HttpServerErrorException
##          - java.util.concurrent.TimeoutException
##          - java.io.IOException
##        ignoreExceptions:
##          - com.yourapp.exception.BusinessException
#
